apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isfrisktilarbeid
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
    outbound:
      external:
        - host: "mqls02.preprod.local"
          ports:
            - port: 1413
        - host: "login.microsoftonline.com"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "dokarkiv.dev-fss-pub.nais.io"
        - host: "oppgave.dev-fss-pub.nais.io"
      rules:
        - application: istilgangskontroll
        - application: ispdfgen
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
          namespace: paw
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: isfrisktilarbeid-db
        diskAutoresize: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: isfrisktilarbeid-serviceuser
  kafka:
    pool: nav-dev
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: KTOR_ENV
      value: "production"
    - name: JOURNALFORING_RETRY_ENABLED
      value: "false"
    - name: MQGATEWAY_NAME
      value: "MQLS02"
    - name: MQGATEWAY_HOSTNAME
      value: "mqls02.preprod.local"
    - name: MQGATEWAY_PORT
      value: "1413"
    - name: MQGATEWAY_CHANNEL_NAME
      value: "Q1_ISFRISKTILARBEID"
    - name: MQ_QUEUE_NAME
      value: "QA.Q1_278.IT00_N2_MLD_FRA_ARENA"
    - name: MQ_QUEUE_NAME_KVITTERING
      value: "QA.Q1_ISFRISKTILARBEID.IT00_N2_KVITT_TIL_MODIA"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: ARBEIDSSOKER_OPPSLAG_CLIENT_ID
      value: "dev-gcp.paw.paw-arbeidssoekerregisteret-api-oppslag-v2"
    - name: ARBEIDSSOKER_OPPSLAG_URL
      value: "http://paw-arbeidssoekerregisteret-api-oppslag-v2.paw"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: DOKARKIV_CLIENT_ID
      value: "dev-fss.teamdokumenthandtering.dokarkiv-q1"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.dev-fss-pub.nais.io"
    - name: OPPGAVE_CLIENT_ID
      value: "dev-fss.oppgavehandtering.oppgave"
    - name: OPPGAVE_URL
      value: "https://oppgave.dev-fss-pub.nais.io"
